# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CSS Playground
description: > # this means to ignore newlines until "baseurl:"
  CSS Playground is a collection of small, interactive tools designed to make working with CSS more fun and approachable. From visualizing tricky properties to quickly generating snippets, it's meant to be a space where you can experiment.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://css-playground.rehanbutt.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown